FROM node:current-alpine3.16

WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY . .

ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm install

# Bundle app source

EXPOSE 8080
ENTRYPOINT [ "npm","run","serve" ]
